// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let _supabase: ReturnType<typeof createClient<Database>> | null = null;

// Lazy initialization of Supabase client
function initializeSupabase() {
  if (_supabase) return _supabase;

  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('Supabase credentials not configured. Some features may not work.');
  }

  _supabase = createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// Note: Supabase client is lazily initialized on first use

export const supabase = new Proxy({}, {
  get: (target, prop) => {
    const client = initializeSupabase();
    return Reflect.get(client, prop);
  }
}) as ReturnType<typeof createClient<Database>>;